import { defineField, defineType } from "sanity";
import { contentStatusField } from "./contentStatus";
import { imageGalleryField, imageWithAltField } from "./fields/imageFields";
import { bookingUrlField, lineInquiryUrlField } from "./fields/linkFields";
import { seoFields } from "./fields/seoFields";
import { textSafetyValidation, urlSafetyValidation } from "./fields/validation";

export const room = defineType({
  name: "room",
  title: "房型資料",
  type: "document",
  groups: [
    { name: "basic", title: "基本資料", default: true },
    { name: "content", title: "內容編輯" },
    { name: "media", title: "圖片與相簿" },
    { name: "links", title: "連結設定" },
    { name: "seo", title: "SEO 設定" },
    { name: "publishing", title: "發布狀態" },
  ],
  fields: [
    defineField({
      name: "property",
      title: "所屬館別",
      type: "reference",
      group: "basic",
      to: [{ type: "property" }],
      weak: true,
      description: "選擇 Love 館或 Tour 館。正式發布前必須確認。",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "roomNumber",
      title: "房號",
      type: "string",
      group: "basic",
      description: "例如 1201。請保留實際房號，方便對應照片與訂房連結。",
      validation: (rule) => [rule.required(), ...textSafetyValidation(rule)],
    }),
    defineField({
      name: "name",
      title: "正式房名",
      type: "string",
      group: "basic",
      description: "不含房號的正式房名，例如地中海豪華雙人房。",
      validation: (rule) => [rule.required(), ...textSafetyValidation(rule)],
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "publishing",
      description: "網址用英文代號，需小寫且不可重複。已產生後請避免任意修改。",
      options: {
        source: "name",
        maxLength: 96,
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "recommendedGuests",
      title: "建議入住人數",
      type: "number",
      group: "basic",
      description: "公開建議入住人數。正式發布前必須確認。",
      validation: (rule) => rule.required().integer().min(1),
    }),
    defineField({
      name: "maximumGuests",
      title: "最多入住人數",
      type: "number",
      group: "basic",
      description: "若尚未確認，請留空；前台不得顯示待確認文字。",
    }),
    defineField({
      name: "bedSetup",
      title: "床型",
      type: "string",
      group: "basic",
      description: "例如一大床、兩大床、一大一小床。",
      validation: (rule) => [rule.required(), ...textSafetyValidation(rule)],
    }),
    defineField({
      name: "extraBedAvailable",
      title: "是否可加床",
      type: "boolean",
      group: "basic",
      initialValue: false,
      description: "只代表可提前詢問，不代表保證可加床或已確認費用。",
    }),
    defineField({
      name: "summary",
      title: "簡短介紹",
      type: "text",
      rows: 3,
      group: "content",
      description: "PoC 可留空；正式介紹待照片與房型特色確認後再補。",
      validation: textSafetyValidation,
    }),
    defineField({
      name: "description",
      title: "詳細介紹",
      type: "text",
      rows: 5,
      group: "content",
      description: "完整房型介紹；未確認可留空，請勿填待確認。",
      validation: textSafetyValidation,
    }),
    defineField({
      name: "amenities",
      title: "設備",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
      description: "一行一個設備。未確認的設備請不要填入。",
      validation: textSafetyValidation,
    }),
    defineField({
      name: "notes",
      title: "注意事項",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
      description: "例如禁菸、加床需提前告知、晚上 10 點後降低音量。",
      validation: textSafetyValidation,
    }),
    imageWithAltField({
      name: "coverImage",
      title: "封面照片",
      description: "房型列表與房型頁使用的封面照片；正式照片未確認前請留空。",
    }),
    imageGalleryField({
      name: "gallery",
      title: "相簿照片",
      description: "房型相簿照片，可拖曳排序；未確認房型對應前請勿標為正式素材。",
    }),
    defineField({
      name: "displayOrder",
      title: "顯示順序",
      type: "number",
      group: "publishing",
      initialValue: 10,
      description: "數字越小越前面。",
      validation: (rule) => rule.required().integer().min(0),
    }),
    defineField({
      name: "odingUrl",
      title: "奧丁丁網址",
      type: "url",
      group: "links",
      description:
        "Legacy PoC 欄位，暫時保留供舊資料讀取；新資料請改填下方「訂房連結 bookingUrl」。未確認前不可啟用正式訂房 CTA。",
      validation: urlSafetyValidation,
    }),
    bookingUrlField,
    lineInquiryUrlField,
    defineField({
      name: "featured",
      title: "是否推薦",
      type: "boolean",
      group: "publishing",
      initialValue: false,
      description: "控制是否可被前台推薦區使用；不代表已正式發布。",
    }),
    ...seoFields,
    contentStatusField,
  ],
  preview: {
    select: {
      title: "name",
      roomNumber: "roomNumber",
      property: "property.propertyKey",
      subtitle: "contentStatus",
      media: "coverImage",
    },
    prepare(selection) {
      return {
        title: `${selection.roomNumber ?? ""} ${selection.title ?? ""}`.trim(),
        subtitle: [selection.property, selection.subtitle].filter(Boolean).join(" / "),
        media: selection.media,
      };
    },
  },
});
